### ISSUE TITLE
fs.mkdir doesn't seem to work anymore - outdated call maybe?

### ISSUE THREAD

**Issue by dmurph** [expalmer/metalsmith-gist#4]
I get the following error when using cache:
```
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at makeCallback (fs.js:168:11)
    at Object.mkdir (fs.js:956:14)
    at Object.makeCacheDir (/.../node_modules/metalsmith-gist/lib/index.js:249:10)
    at Gist.app.writeCachedData (/.../node_modules/metalsmith-gist/lib/index.js:202:16)
    at /.../node_modules/metalsmith-gist/lib/index.js:155:12
    at /.../node_modules/q/q.js:1249:26
    at _fulfilled (/.../node_modules/q/q.js:854:54)
    at /.../node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/.../node_modules/q/q.js:816:13)
    at /.../node_modules/q/q.js:570:49 {
  code: 'ERR_INVALID_CALLBACK',
  gist: {
    fullName: 'expalmer/4bc6203dc2a3f7134e78',
    name: 'expalmer/4bc6203dc2a3f7134e78',
    file: undefined
  }
}
```

Looks like mkdir needs a callback:
https://nodejs.org/api/fs.html#fs_fs_mkdir_path_options_callback

**Comment by dmurph** [comment]
Spot:
https://github.com/expalmer/metalsmith-gist/blob/master/lib/index.js#L247

**Comment by expalmer** [comment]
Hi! I will see it soon.  Thanks for the alert!
